import { APP_DESCRIPTION, APP_NAME, APP_URL } from "@/lib/constants";
import { getMiniAppEmbedMetadata } from "@/lib/utils";
import type { Metadata } from "next";

export const revalidate = 86400;

// This is an example of how to generate a dynamically generated share page based on fid:
// Sharing this route e.g. exmaple.com/share/123 will generate a share page for fid 123,
// with the image dynamically generated by the opengraph-image API route.
export async function generateMetadata({
  params,
}: {
  params: Promise<{ fid: string }>;
}): Promise<Metadata> {
  const { fid } = await params;
  const imageUrl = `${APP_URL}/api/opengraph-image?fid=${fid}`;

  return {
    title: `${APP_NAME} - Share`,
    openGraph: {
      title: APP_NAME,
      description: APP_DESCRIPTION,
      images: [imageUrl],
    },
    other: {
      "fc:frame": JSON.stringify(getMiniAppEmbedMetadata(imageUrl)),
    },
  };
}

export default function SharePage() {
  return (
    <>
      <meta httpEquiv="refresh" content="0;url=/" />
      <main className="min-h-screen bg-slate-950 text-white" />
    </>
  );
}
